added pagination for arguments
Monstarrrr/rebutify pull request #240
Opened 2024-07-02 17:48 UTC by purple-void

we also added some comments

2024-07-03 22:06 UTC, Monstarrrr requested changes
1. Why are we making pagination for arguments specifically? Isn't pagination the same logic regardless of the type of content?  
Use django setting to apply to any endpoint  

2. The front-end should be able to decide on how many items per page there are. Do not hard-code it in the back-end unless as a default value

2024-07-04 20:15 UTC, seporterfield commented on backend/.template-env
> +PAGE_SIZE=
missing short comment

2024-07-04 20:15 UTC, seporterfield commented on backend/rebutify/settings.py
> +    "PAGE_SIZE": os.getenv("PAGE_SIZE", 10),
wrap with `int()` type conversion since os.getenv will return a string if the value is set

2024-07-04 20:16 UTC, seporterfield requested changes
commented 2 changes
looks great and nice job!

2024-07-04 23:10 UTC, Monstarrrr commented
> @Monstarrrr we changed pagination to apply globally. PAGE_SIZE is set in env. Does that work for the front-end?

The page size should be part of the request body or parameters e.g. ``api/posts?size=15&page=1``

2024-07-06 07:21 UTC, seporterfield approved these changes

2024-07-06 17:01 UTC, seporterfield commented
> @seporterfield we think the checks are wrong. we can't reproduce the error in our code

did you read the error/output of the checks?

2024-07-06 18:00 UTC, seporterfield commented
The way we're parsing .env variables has a side effect of any empty variables in .env being parsed as the empty string instead of `None` which is kinda annoying but I haven't been able to find a solution that doesn't make things even harder for people trying to use our project.

Fix option 1:
Put `sed -i 's/^PAGE_SIZE=$/PAGE_SIZE=20/' .env` in the "Write dummy .env" step in the workflow file. This is fitting for variables that need to be changed to something for production that is different than the default that might be provided in .template-env

Fix option 2:
Make `PAGE_SIZE=20` in .template-env
This is fitting if we want a page size of 20 by default for anyone setting up their own instance of Rebutify.

2024-07-06 19:34 UTC, seporterfield commented
> We fixed it for now with `"PAGE_SIZE": int(os.getenv("PAGE_SIZE", "10") or "10")`

this is probably the best long term strategy for non-string env vars, looks great

2024-07-07 13:04 UTC, seporterfield approved these changes

2024-07-07 20:21 UTC, Monstarrrr approved these changes
To the rescue

2024-07-07 20:21 UTC, merged