Opened Decision: Automating API Docs
Monstarrrr/rebutify pull request #78
Opened 2024-05-27 21:32 UTC by seporterfield

2024-05-28 00:14 UTC, Monstarrrr reviewed
For the front-end I only care about the doc having good UX/UI, and redoc looks good.

2024-05-29 01:25 UTC, purple-void approved these changes

2024-05-29 02:09 UTC, purple-void commented on docs/decisions/architecture/automating-api-docs_DECISION.md
> +    - @purple-void [1 <-> 5] /5
3.5 for us

2024-05-29 02:10 UTC, purple-void requested changes

2024-05-29 02:10 UTC, purple-void commented on docs/decisions/architecture/automating-api-docs_DECISION.md
> +    - @purple-void [1 <-> 5] /5
3.5 for us

2024-05-29 02:16 UTC, merged